// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgsghzdjsnsjkaghsumd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxnc2doemRqc25zamthZ2hzdW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NDc0ODAsImV4cCI6MjA3MzIyMzQ4MH0.MgiA9QVpt9LQqfV4r-eT9jFaL4qu3J729XMBtQ9h8NU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});